language: node_js

sudo: false

notifications:
  email:
  - wznarutone326@gmail.com
  - wznaruto326@163.com

node_js:
  - 8.11.1

script:
- |
    if [ "$TEST_TYPE" = test ]; then
      npm test -- --coverage
    else
      npm run $TEST_TYPE
    fi
env:
  matrix:
  - TEST_TYPE=test
